const habilidadesButton = document.querySelector('.habilidades-button');
const habilidadesMenu = document.querySelector('.habilidades');
const descripcionHabilidad = document.querySelector('.descripcion-habilidad');
const habilidades = document.querySelectorAll('.habilidades ul li');

habilidadesButton.addEventListener('click', function () {
    if (habilidadesMenu.style.display === 'block') {
        habilidadesMenu.style.display = 'none';
        descripcionHabilidad.style.display = 'none';
    } else {
        habilidadesMenu.style.display = 'block';
    }
});

habilidades.forEach(function (habilidad) {
    habilidad.addEventListener('click', function () {
        const descripcion = obtenerDescripcionHabilidad(habilidad.getAttribute('data-habilidad'));
        descripcionHabilidad.innerHTML = `<p>${descripcion}</p>`;
        descripcionHabilidad.style.display = 'block';
        habilidadesMenu.style.display = 'none'; // Cierra el menú al hacer clic en una habilidad
    });
});

function obtenerDescripcionHabilidad(nombreHabilidad) {
    const descripciones = {
        //GUERRERO
        'Defensa Absoluta': '<span style="color: gold;">Otorga al usuario una inmunidad total contra los ataques enemigos.</span> Esta habilidad le permite al usuario adoptar una postura defensiva inquebrantable que lo vuelve prácticamente invulnerable a cualquier tipo de daño. Al activar esta habilidad, el usuario puede resistir cualquier ataque, desde golpes físicos hasta ataques mágicos, <span style="color: chartreuse;"> y los desvía con facilidad</span>, sin importar la fuerza del oponente. <span style="color: darkslateblue;">La unica debilidad de esta habilidad es que solo eres inmune a un ataque.</span> <span style="color: crimson;"> Esta habilidad no puede ser usada con frecuencia.</span>',
        'Golpe Feroz': 'El guerrero <span style="color: gold;">concentra toda su fuerza en un poderoso golpe</span>, capaz de infligir daño significativo a su objetivo. <span style="color: darkslateblue;"> Esta habilidad requiere un tiempo de carga de 5 segundos</span>, pero su potencia es capaz de hacer tambalear incluso a los enemigos más fuertes. <span style="color: crimson;">Mientras cargas la habilidad quedas indefenso y vulnerable a los ataques enemigos.</span>',
        'Parry': 'Esta habilidad no solo lo protege de los ataques físicos entrantes, sino que también le <span style="color: aqua;">brinda la oportunidad de convertir la defensa en un feroz ataque,</span> lo que lo convierte en un guerrero temible y letal. <br> <span style="color: gold;">No importa cuán poderoso sea el ataque físico,</span> el Guerrero puede <span style="color: violet;">desviarlos con facilidad</span> y sin esfuerzo aparente. Su destreza en el desvío es tan precisa que <span style="color:blue;">los ataques desviados no causan ningún daño</span> al Guerrero. <br> Tras desviar un ataque, el Guerrero aprovecha la oportunidad para lanzar un <span style="color: crimson;">contraataque letal.</span> Sus enemigos quedan <span style="color: darkseagreen;">momentáneamente aturdidos</span> por la sorpresa y la incredulidad de que sus ataques hayan sido desviados.',
        'Intencion de la Espada': 'La "Intención de la Espada" es la manifestación suprema de la habilidad de un espadachín. Se trata de una <span style="color: gold; text-shadow: 0px 2px 5px gold;">técnica legendaria</span> que permite al usuario liberar un <span style="color: rgb(129, 129, 235);">tajo de energía increíblemente afilado,</span> capaz de cortar incluso los materiales más resistentes, como el mithril. Sin embargo, esta técnica <span style="color: rgb(106, 228, 106);">no se trata solo de fuerza bruta, sino de la perfecta sintonía entre el espadachín y su espada.</span> <br> Cuando un espadachín logra comprender el camino de la espada en su forma más pura, se convierte en un <span style="color: blueviolet; text-shadow: 0px 2px 10px violet;">Maestro de la Espada.</span> Solo unos pocos a lo largo de la historia han alcanzado este nivel de destreza y maestría. La "Intención de la Espada" representa la culminación de años de entrenamiento, disciplina y conexión con la propia arma. <br> El proceso de desencadenar esta técnica es un acto de <span style="color: rgb(56, 205, 212);">profunda concentración y enfoque.</span> El espadachín debe conectarse espiritualmente con su espada, sintiendo cada detalle de su filo, su peso y su equilibrio. Cuando el momento es propicio y la conexión es perfecta, el espadachín puede liberar una <span style="color: red;">onda de energía en forma de corte, que se desplaza a una velocidad asombrosa y puede atravesar cualquier obstáculo en su camino.</span> <br> Sin embargo, el uso de la "Intención de la Espada" <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">no es gratuito.</span> Tiene un <span style="color: cadetblue;">impacto significativo en la fuerza mental del espadachín,</span> <span style="color: rgb(55, 14, 89); text-shadow: 0px 0px 10px white;">dejándolo agotado y vulnerable después de su uso.</span> Debido a esta carga mental, <span style="color: rgb(220, 130, 20);">solo puede ser utilizado una vez cada 24 horas,</span> lo que significa que debe ser reservado para <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">momentos verdaderamente críticos.</span>',
        'Corte Heptagonal': 'El Corte Heptagonal es una <span style="color: gold;">manifestación de pura destreza y maestría en el arte de la espada.</span> Este ataque, <span class="intencionEspada">imbuido con la Intención de la Espada,</span> <span style="color: crimson;">canaliza el poder de siete cortes simultáneos en un solo tajo de energía letal.</span> La espada del usuario irradia con un resplandor brillante y cortante mientras se desencadena esta habilidad. <br> Cuando el Corte Heptagonal se libera, atraviesa el aire con una velocidad vertiginosa y precisión mortal. <span style="color: skyblue;">Cualquier objeto o enemigo en su camino es dividido y desgarrado sin piedad. Es capaz de cortar incluso a través de la magia y las defensas más formidables.</span> <br> Sin embargo, este ataque excepcionalmente poderoso <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">tiene una debilidad fundamental.</span> La carga mental y física de canalizar semejante poder es abrumadora. <span style="color: royalblue;">Después de ejecutar el Corte Heptagonal, el usuario queda exhausto, su cuerpo y mente agotados por el esfuerzo sobrehumano.</span>  <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">Esto lo deja vulnerable y sin capacidad de luchar,</span> convirtiendo esta habilidad en un último recurso desesperado, <span style="color: darkmagenta;">reservado para situaciones de vida o muerte.</span>',
        //MAGO
        //FUEGO
        'Bola de Fuego': 'Esta es la habilidad elemental más <span style="color: cornflowerblue;">básica</span>  del fuego. El mago genera una pequeña esfera de fuego en la palma de su mano y la lanza hacia el objetivo. <span style="color: orangered;">La bola de fuego es de tamaño modesto, su explosion es pequeña y tiene un alcance limitado,</span> pero puede <span style="color: darkviolet;">causar quemaduras menores</span> en el impacto.',
        'Flecha de Fuego': 'Es una habilidad de magia <span class="fuego">elemental de fuego</span> que permite crear y lanzar <span style="color: crimson;">proyectiles ardientes de fuego comprimido.</span> Esta habilidad se caracteriza por su <span style="color: blue;">impresionante poder de penetración y la asombrosa velocidad con la que viajan los proyectiles.</span> Cuando se canaliza el mana en esta habilidad, se forma una flecha de fuego en la palma de la mano que, una vez liberada, atraviesa el aire con una velocidad vertiginosa y un <span style="color: lightgreen;">alcance considerable.</span> <br> La principal ventaja de la Flecha de Fuego radica en su capacidad para penetrar las defensas de los oponentes, ya que <span style="color: violet;">puede atravesar armaduras y barreras con relativa facilidad.</span> Esto la convierte en un recurso eficaz para enfrentar a enemigos fuertemente protegidos. Sin embargo, su gran velocidad puede ser una <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">desventaja</span> cuando se trata de precisión a largas distancias, ya que <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">es difícil de acertar al objetivo a grandes rangos, lo que requiere una destreza y precisión excepcionales por parte de quien la usa.</span> <span style="color: cyan;">En combate cercano,</span> la Flecha de Fuego es una arma formidable, capaz de infligir daño significativo y superar las defensas de los oponentes.',
        'Llamarada Ascendente': 'Es una formidable habilidad que <span class="fuego">emana fuego del suelo hacia el cielo,</span> desplegando un espectáculo ardiente y demoledor. Esta magia es conocida por su <span style="color: lightgreen;">impresionante alcance y su tremendo poder destructivo,</span> lo que la convierte en un recurso excepcional para situaciones que requieren ataques a gran escala. <br> Cuando se activa Llamarada Ascendente, <span style="color: dodgerblue;">el usuario canaliza su mana hacia el suelo, encendiendo una chispa mágica que recorre el terreno. Esta chispa se convierte rápidamente en una columna de fuego que se eleva hacia el cielo en una explosión feroz y majestuosa.</span> La columna de fuego puede abarcar una amplia área, afectando tanto a objetivos cercanos como a aquellos a cierta distancia. Es particularmente <span style="color: darkgoldenrod;">eficaz contra grupos de enemigos o en situaciones en las que la destrucción masiva es necesaria.</span> <br> La intensidad de la Llamarada Ascendente no solo reside en su capacidad para arrasar a los oponentes, sino también en su durabilidad. <span style="color: gold;">Puede mantenerse durante un tiempo, controlada por el usuario, lo que le brinda flexibilidad en el campo de batalla.</span> <br> Sin embargo, <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">no todo es beneficio con esta habilidad, ya que el poder que consume y la complejidad de su control pueden ser un desafío. Un mal manejo podría llevar al agotamiento de la energía del usuario o incluso al desencadenamiento accidental de la magia, poniendo en peligro a aliados y al propio lanzador.</span>',
        //AGUA
        'Proyectil de Agua': 'Esta es una habilidad elemental <span style="color: cadetblue;">básica</span> del agua. El mago crea un <span style="color: aqua;">proyectil de agua comprimida</span> y lo dispara hacia su objetivo. Aunque <span style="color: crimson;">no es particularmente poderoso,</span> el proyectil de agua puede <span style="color: greenyellow;">empapar al objetivo</span> y, en condiciones adecuadas, puede <span style="color: midnightblue;">apagar pequeños incendios.</span>',
        'Estacas de Hielo': 'Las <span class="agua">Estacas de Hielo</span> son una poderosa habilidad mágica que permite al usuario crear <span style="color: crimson;">proyectiles afilados hechos de hielo y lanzarlos a alta velocidad hacia un objetivo.</span> Esta habilidad se caracteriza por su naturaleza ofensiva y letal, siendo una forma efectiva de infligir daño a los enemigos. <br> La principal característica de esta habilidad es su capacidad para crear proyectiles de hielo afilados que <span style="color: darkorchid;">pueden atravesar tejidos, armaduras y objetos con facilidad, mientras no sean de un material muy resistente.</span> Estos proyectiles se lanzan a alta velocidad, lo que los hace difíciles de esquivar. <br> La efectividad de las <span class="agua">Estacas de Hielo</span> puede <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">depender de la disponibilidad de agua o humedad en el entorno, lo que podría limitar su uso en áreas secas o desérticas.</span> Además, los enemigos con resistencia al frío o habilidades relacionadas con el fuego pueden ser menos vulnerables a este tipo de magia. Cabe destacar que <span style="color:lightgreen;">lanzar múltiples</span> <span class="agua">Estacas de Hielo</span> <span style="color: lightgreen;">consume una cantidad significativa de energía mágica,</span> por lo que su uso debe ser estratégico para evitar la fatiga.',
        'Escudo de Agua': 'Es una habilidad mágica de defensa que permite al usuario crear una <span style="color: aquamarine;">sólida esfera de agua a su alrededor, protegiéndolo de ataques tanto físicos como mágicos sin importar su intensidad.</span> Esta habilidad se destaca por su versatilidad en la protección y su <span style="color: crimson;">capacidad para resistir un solo ataque sin importar cuán poderoso sea.</span> <br> Cuando el usuario activa <span class="agua">Escudo de Agua,</span> canaliza su mana y <span style="color: mediumseagreen;">utiliza la humedad o el agua presente en el entorno para formar una esfera que lo envuelve por completo.</span> La esfera actúa como una barrera protectora, absorbiendo y dispersando la energía de cualquier ataque que la alcance. <br> Una de las ventajas clave de <span class="agua">Escudo de Agua</span> es su resistencia a la intensidad del ataque. Puede <span style="color: deeppink;">defender contra tanto ataques físicos como mágicos,</span> desde golpes de espada hasta <span class="rayo">rayos destructores,</span> y sigue siendo efectiva. Esto brinda al usuario una gran tranquilidad, ya que sabe que su escudo puede mantenerse firme frente a cualquier amenaza. <br> Sin embargo, <span class="agua">Escudo de Agua</span> tiene sus propias limitaciones. <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;"> Requiere la presencia de agua o humedad en el entorno para funcionar,</span> lo que puede ser un problema en áreas secas o en situaciones de combate en lugares áridos. Además, <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">esta habilidad solo puede bloquear un solo ataque; una vez que lo ha hecho, el escudo se desvanece.</span> Por lo tanto, el usuario debe elegir sabiamente cuándo activar esta habilidad para maximizar su efectividad.',
        //VIENTO
        'Tajo de Viento': 'Esta es una habilidad elemental <span style="color: cadetblue;">básica</span> de viento. El mago realiza un <span style="color: lightgreen;">rápido movimiento de su mano,</span> creando una <span style="color: darkred;">cuchilla de viento afilada</span> que se lanza hacia el enemigo. Aunque <span style="color: blueviolet;">no causa daño devastador,</span> puede <span style="color: gold;">cortar superficialmente y desequilibrar al objetivo.</span>',
        'Impulso': 'Es una magia de viento <span style="color: lightpink;">altamente versátil,</span> que permite al usuario <span style="color: lightgreen;">controlar las corrientes de aire a su alrededor</span> con una maestría impresionante. Aunque <span style="color: crimson;">no se considera una magia ofensiva,</span> su aplicabilidad se extiende mucho más allá. Gracias a ella es posible realizar: <br> <span style="color: darkviolet;">● Saltos Elevados:</span> lo cual permite alcanzar lugares que normalmente son inalcanzables para una persona común. <br> <span style="color: darkviolet;">● Aumento de Velocidad:</span> permitiendo generar un impulso para alcanzar un lugar de forma rápida o evadir ataques. <br> <span style="color: darkviolet;">● Maniobras Acrobáticas:</span> como giros o cambios de dirección imprevistos, ya sea en el aire o en tierra. <br> <span style="color: darkviolet;">● Evitar Caídas Peligrosas:</span> cuando se cae de una gran altura, esta habilidad permite aterrizar de forma controlada y segura.',
        'Torbellino de Viento': 'Es una magia poderosa que permite al usuario crear un <span class="viento">remolino de cuchillas afiladas de viento que se desplazan con gran velocidad y cortan todo lo que se encuentra en su camino.</span> Esta habilidad <span style="color: gold;">destaca por su alcance y capacidad para infligir daño a múltiples objetivos a la vez.</span> <br> Cuando el usuario canaliza su mana para activar <span class="viento">Torbellino de Viento,</span> genera un <span style="color: mediumvioletred;">vórtice de energía en el área designada. Este vórtice toma la forma de cuchillas de viento que giran a una velocidad impresionante.</span> Las cuchillas son lo <span style="color: slateblue;">suficientemente afiladas como para cortar a través de objetos sólidos,</span> incluidas las defensas de los oponentes, lo que la convierte en una magia formidable para el combate. <br> La gran ventaja de <span class="viento">Torbellino de Viento</span> es su alcance. <span style="color: mediumseagreen;">El vórtice puede extenderse a una distancia considerable, permitiendo al usuario atacar a múltiples oponentes simultáneamente o alcanzar a un solo objetivo que se encuentra lejos.</span> Esto es especialmente útil en situaciones en las que el usuario se enfrenta a grupos de enemigos o necesita mantener una distancia segura de su oponente. <br> Sin embargo, <span class="viento">Torbellino de Viento</span> también tiene sus propias limitaciones. <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">Su gran alcance y potencia requieren una cantidad significativa de mana, lo que puede llevar a la fatiga del usuario si se utiliza en exceso.</span>',
        //RAYO
        'Electrocutar': 'La habilidad elemental más <span style="color: cadetblue;">básica</span> del rayo. El mago emite una <span style="color: gold;">pequeña descarga eléctrica</span> desde sus dedos hacia el objetivo. Aunque es una habilidad de bajo nivel, puede <span style="color: brown;">causar molestias y calambres si alcanza su objetivo.</span>',
        'Rayo Destructor': 'Es una formidable habilidad mágica que <span style="color: crimson;">se caracteriza por su inmenso poder de ataque,</span> tal como sugiere su nombre. <span style="color: darkorchid;">Este hechizo es capaz de destruir prácticamente cualquier cosa que impacte, reduciéndola a cenizas o fragmentos.</span> El <span class="rayo">Rayo Destructor</span> se manifiesta como un relámpago de energía concentrada que <span style="color: gold;">viaja a una velocidad tan vertiginosa que resulta imposible de seguir con los ojos.</span> Lo único que suele quedar a la vista es una fugaz imagen remanente del poderoso rayo. <br> Sin embargo, a pesar de su impresionante potencia, el <span class="rayo">Rayo Destructor</span> <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">posee ciertas debilidades que limitan su uso.</span> La más destacada de ellas es que <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">solo puede ser utilizado una vez cada veinticuatro horas.</span> Esta restricción temporal asegura que el mago no haga un uso indiscriminado de esta peligrosa magia. <br> Otra limitación significativa es la cantidad masiva de mana requerida para invocar el <span class="rayo">Rayo Destructor.</span> Debido a su naturaleza devastadora, <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">este hechizo consume una cantidad sustancial de energía mágica.</span> Como resultado, los magos que deseen utilizarlo deben tener reservas de mana considerables y estar dispuestos a agotar una parte sustancial de ellas. La falta de suficiente mana puede impedir la invocación de esta magia. <br> El <span class="rayo">Rayo Destructor</span> es una habilidad sumamente temible y <span style="color: aqua;">suele ser reservada para situaciones extremas o enfrentamientos críticos donde su poder destructivo puede inclinar la balanza.</span> Su uso requiere una planificación cuidadosa y un manejo responsable, ya que sus limitaciones temporales y la demanda de mana son aspectos cruciales a considerar.',
        //TIERRA
        'Proyectil de Roca': 'Esta es una habilidad elemental <span style="color: cadetblue;">básica</span> de tierra. El mago <span style="color: saddlebrown;">manipula la tierra cercana</span> para crear un proyectil de roca que lanza hacia el enemigo. Aunque <span style="color: darkorange;">no es particularmente grande ni poderoso,</span> puede <span style="color:lightseagreen;">golpear al objetivo con fuerza moderada.</span> <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">Su única debilidad es que es muy predecible, resultando en que sea facil de bloquear o evadir.</span>',
        'Barrera de Tierra': 'La <span class="tierra">Barrera de Tierra</span> es una magia que aprovecha el entorno, <span style="color: gold;">utilizando tierra o arena circundante para erigir una sólida pared defensiva.</span> Esta habilidad permite a los usuarios crear una <span style="color: cyan;">barrera física que puede bloquear eficazmente una amplia gama de ataques, ya sean mágicos o físicos.</span> <br> La utilidad principal de esta habilidad radica en su capacidad para <span style="color: violet;">defenderse de los ataques enemigos de forma rápida,</span> ya que pueden rápidamente <span style="color: mediumpurple;">levantar una pared de tierra en respuesta a un ataque, lo que brinda una defensa instantánea y versátil en el campo de batalla.</span> <br> Sin embargo, la <span class="tierra">Barrera de Tierra</span> tiene limitaciones importantes. <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">Esta magia solo puede bloquear en la dirección en la que se erige, lo que significa que los ataques desde otras direcciones pueden representar una amenaza.</span> Además, <span style="color: rgb(42, 170, 140);">esta habilidad depende de la disponibilidad de tierra o arena en el entorno.</span> En lugares donde estos elementos no están presentes, como en áreas rocosas o acuáticas, no se puede utilizar la <span class="tierra">Barrera de Tierra,</span> lo que puede dejar al usuario vulnerable. Además, esta magia <span style="color: cornflowerblue;">no puede aguantar muchos golpes seguidos o una magia que sea constante.</span>',
        //OSCURIDAD
        'Maldicion': 'Es una magia <span style="color: cornflowerblue;">especializada en la aplicación de debuffs</span> a los objetivos. <span style="color: crimson;">Esta habilidad,</span> a diferencia de muchas otras magias, <span style="color: crimson;">no busca causar daño directo o infligir heridas, sino más bien debilitar gradualmente al oponente.</span> <span style="color: aqua;">Los efectos de Maldición no son inmediatos, sino que se desarrollan con el tiempo,</span> volviéndose progresivamente más evidentes a medida que transcurren los segundos. <br> Al principio, los debuffs aplicados por Maldición pueden parecer insignificantes o imperceptibles, lo que puede llevar a los oponentes subestimar el poder de esta magia. Sin embargo, <span style="color: blueviolet;">a medida que pasa el tiempo, los efectos se acumulan y se vuelven cada vez más notorios.</span> Estos debuffs pueden variar desde disminuir la velocidad de movimiento del objetivo, reducir su fuerza física, consumir gradualmente su vitalidad o incluso limitar el uso de sus habilidades mágicas. <br> <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">La desventaja de la magia de Maldición es que no es efectiva en situaciones donde se necesita un resultado rápido, ya que sus efectos toman tiempo para desarrollarse por completo.</span> Es crucial para los usuarios de esta magia ser pacientes y estratégicos, buscando aprovechar los debuffs acumulados en el transcurso de una batalla prolongada.',
        //LUZ
        'Sanacion': 'Es una habilidad de <span class="luz">Magia de Luz</span> con el poder de <span style="color: lightgreen;">curar heridas y restaurar la salud de un individuo.</span> Esta magia es altamente versátil y <span style="color: blueviolet;">puede abordar una amplia variedad de lesiones, desde cortes menores hasta huesos rotos y heridas graves.</span> Funciona a través de la manipulación del mana para estimular la regeneración celular y acelerar la curación. <span style="color: crimson;">La cantidad de mana requerida varía según la gravedad de la herida.</span> <br> <span style="color: aqua;">Tiene la capacidad de restaurar extremidades amputadas, aunque este proceso requiere una cantidad considerable de mana.</span> Cuanto más reciente sea la amputación, más efectiva será la Sanación. <br> Además de tratar heridas físicas, <span style="color: darkorange;">Sanación puede utilizarse para aliviar condiciones médicas como enfermedades y envenenamientos, especialmente en las primeras etapas de la enfermedad.</span> <br> <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">El uso excesivo de Sanación puede agotar rápidamente el mana y causar agotamiento. Además, la magia no puede contrarrestar completamente la inevitabilidad de la muerte en casos de heridas mortales.</span>',
        'Purificacion': 'Es una habilidad <span style="color: gold;">especializada en la eliminación rápida y eficiente de no muertos de bajo rango, como zombies o esqueletos, que carecen de inteligencia y son controlados por fuerzas oscuras.</span> Además, <span style="color: crimson;">tiene la capacidad de purificar a no muertos de mayor rango, como espectros o dragones, pero solo cuando están debilitados o heridos, lo que dificulta su purificación.</span> <br> Esta habilidad funciona a través de la manipulación del mana para invocar la pureza y la luz, que actúan como una fuerza repelente contra la oscuridad que anima a los no muertos. <span style="color: lightgreen;">Los no muertos de bajo rango, al carecer de una voluntad o inteligencia significativas, pueden ser purificados de inmediato con una cantidad mínima de mana.</span> <br> Sin embargo, los no muertos de mayor rango son más resistentes a la purificación y solo pueden ser liberados de la maldición cuando están heridos o debilitados. <span style="color: blueviolet;">La cantidad de mana requerida para purificar no muertos de alto rango es significativamente mayor y puede variar según el tipo y la gravedad de la herida.</span> <br> Además de su capacidad para purificar no muertos, <span style="color: aqua;">Purificación también puede usarse para liberar a personas de maldiciones que afectan su cuerpo o alma.</span> Esta habilidad es especialmente valiosa en situaciones en las que alguien está bajo la influencia de una maldición oscura o maleficio. El proceso de purificación implica la disipación de la oscuridad y la restauración de la pureza del afectado. <br> <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">Es importante destacar que el uso excesivo de Purificación en no muertos de alto rango puede agotar rápidamente el mana del usuario, lo que puede dejarlo vulnerable en combate.</span>',
        //ESPACIO
        'Fisura Espacial': 'Es una habilidad de magia avanzada que permite al usuario <span class="espacial">rasgar el tejido del espacio mismo.</span> Con esta magia, se pueden crear <span style="color: crimson;">fisuras dimensionales afiladas que tienen la capacidad de cortar prácticamente cualquier cosa que encuentren en su camino.</span> La fisura espacial es un fenómeno temible, ya que desafía las leyes normales de la física y puede atravesar materiales y defensas con facilidad. <br> Para usar Fisura Espacial, es necesario canalizar una gran cantidad de mana para romper el espacio. Cada fisura requiere una inversión significativa de energía mágica, lo que la hace costosa en términos de agotamiento de mana. <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">Debido a esta alta demanda de mana, la magia de Fisura Espacial no es algo que se pueda usar repetidamente sin un buen suministro de energía mágica.</span> <br> Esta habilidad es particularmente devastadora en combate, ya que <span style="color: aqua;">puede cortar a través de escudos, armaduras e incluso la materia más resistente.</span> Sin embargo, debido a su alto costo en términos de mana, los magos deben usarla con cuidado y precisión.',
        'Teletransportacion': 'Es una habilidad mágica extraordinaria que <span class="espacial">permite al usuario desplazarse instantáneamente a cualquier lugar que esté dentro de un radio de 500 metros sin la necesidad de moverse físicamente.</span> Esta habilidad es considerada una de las magias más avanzadas y versátiles, ya que otorga una movilidad y flexibilidad excepcionales. <br> Para utilizar la Teletransportación, el mago debe canalizar una <span style="color: crimson;">cantidad significativa de mana, que varía según la distancia.</span> Una vez que se ha acumulado suficiente energía mágica, el mago puede enfocar su intención en el lugar de destino y, en un abrir y cerrar de ojos, desaparecerá de su ubicación actual y reaparecerá en el lugar deseado. <br> Es importante destacar que la Teletransportación es una habilidad que <span style="color: black; text-shadow: 0px 0px 10px crimson; text-shadow: -1px 2px 10px crimson;">requiere una gran reserva de mana, y su uso constante puede agotar rápidamente los recursos mágicos del usuario.</span> Por lo tanto, es fundamental que el mago administre su mana con cuidado y utilice la Teletransportación estratégicamente.'
    };

    return descripciones[nombreHabilidad] || 'No se encontró descripción para esta habilidad.';
}

function abrirEnNuevaVentana() {
    alert("Este enlace se abrirá en una nueva pestaña");
}

const menuButton = document.querySelector('.menu-button');

menuButton.addEventListener('click', function() {
  descripcionHabilidad.style.display = 'none';
});